[workspace]
resolver = "3"
members = [
  "crates/learning/ntsc-openfx",
  "crates/learning/ofx-guide-1-basic-machinery",
  "crates/learning/ofx-guide-2-invert", "crates/learning/ofx-guide-3-gain",
  "crates/openfx-bindings",
  "crates/openfx-helpers",
  "xtask",
]

[workspace.package]
license = "MIT"
repository = "https://github.com/umajho/openfx-playground"

[workspace.lints]

[workspace.dependencies]
openfx-bindings = { version = "0.1.7", path = "crates/openfx-bindings" }
openfx-helpers = { version = "0.1.0", path = "crates/openfx-helpers" }

bindgen = "0.72"
tracing = "0.1.44"
